<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportType->label() }}</title>
    <style>
        body {
            font-family: DejaVu Sans,
            sans-serif;
            font-size: 11px;
            margin: 0;
        }
        h1 {
            font-size: 18px;
            margin-bottom: 4px;
        }
        .header {
            border-collapse: collapse;
            border: none;
        }
        table.header td,
        table.header th {
            border: none;
        }
        .meta {
            color: #555;
            margin-bottom: 12px;
        }
        .report-title {
            text-align: right;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }
        th {
            background: #e5e7eb;
            padding: 6px;
            text-align: left;
            border: 1px solid #ccc;
        }
        td {
            padding: 6px;
            border: 1px solid #ccc;
        }
        .totals {
            background: #f3f4f6;
            font-weight: bold;
        }
        .numbers th {
            background: #f4f4f5;
        }
        table.data-table tr {
            page-break-inside: avoid;
        }
    </style>
</head>
<body>
    <table class="header">
        <tbody>
            <tr>
                <td>
                    <h1>Mimo Playcafe</h1>
                </td>
                <td>
                    <h1 class="report-title">{{ $reportType->label() }}</h1>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="meta">
        Date Range: {{ $report['start_date'] }} to {{ $report['end_date'] }}<br>
        Generated: {{ $report['generated_at'] }}
    </div>

    <table class="data-table">
        <thead>
            <tr>
                @foreach(array_keys((array) ($report['data']->first() ?? [])) as $header)
                    <th>{{ str_replace('_', ' ', ucfirst($header)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($report['data'] as $row)
                <tr>
                    @foreach($row as $value)
                        <td>{{ is_iterable($value) ? collect($value)->implode(' | ') : $value }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($report['data']->first() ?? []) }}">No data found for the selected period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    <br><br><br>
    <table>
        <thead>
            <tr>
                <th>Transactions</th>
                <th>Total Sales</th>
                <th>Total Duration</th>
                <th>Total Socks</th>
            </tr>
            <tr class="numbers">
                <th>{{ number_format( $report['totals']['total_transactions'] ?? 0) }}</th>
                <th>₱{{ number_format($report['totals']['total_sales'] ?? 0, 2) }}</th>
                <th>{{ number_format($report['totals']['total_duration'] ?? 0, 2) }} ₱/hour</th>
                <th>{{ number_format($report['totals']['total_socks']) }}</th>
            </tr>
        </thead>
    </table>
    <br>
    <small>Reports generated by: <italic>Right Apps Incorporated</italic></small>
</body>
</html>
